function cerrar_help(){
    document.getElementById("rectangle_app").style.visibility = "hidden"
    document.getElementById("rectangle2_app").style.visibility = "hidden"
    document.getElementById("rectangle3_app").style.visibility = "hidden"
    document.getElementById("rectangle4_app").style.visibility = "hidden"
    document.getElementById("rectangle5_app").style.visibility = "hidden"
    document.getElementById("rectangle6_app").style.visibility = "hidden"
    document.getElementById("name_app").style.visibility = "hidden"
    document.getElementById("line_app").style.visibility = "hidden"
    document.getElementById("line2_app").style.visibility = "hidden"
    document.getElementById("line3_app").style.visibility = "hidden"
    document.getElementById("text_app").style.visibility = "hidden"
    document.getElementById("text2_app").style.visibility = "hidden"
    document.getElementById("text3_app").style.visibility = "hidden"
}
function mostrar_help(){
    document.getElementById("rectangle_app").style.visibility = "visible"
    document.getElementById("rectangle2_app").style.visibility = "visible"
    document.getElementById("rectangle3_app").style.visibility = "visible"
    document.getElementById("rectangle4_app").style.visibility = "visible"
    document.getElementById("rectangle5_app").style.visibility = "visible"
    document.getElementById("rectangle6_app").style.visibility = "visible"
    document.getElementById("name_app").style.visibility = "visible"
    document.getElementById("line_app").style.visibility = "visible"
    document.getElementById("line2_app").style.visibility = "visible"
    document.getElementById("line3_app").style.visibility = "visible"
    document.getElementById("text_app").style.visibility = "visible"
    document.getElementById("text2_app").style.visibility = "visible"
    document.getElementById("text3_app").style.visibility = "visible"
}